### ISSUE TITLE
[Suggestion] Example mods

### ISSUE THREAD

**Issue by Raelaziel** [Valheim-Modding/Jotunn#129]
Howdy!

I love that simplifying and making the mod-makers life easier, even the wannabe "mod-makers" with round "0" knowledge about writing stuff with C# or managin the Unity, but well... thanks to Jotunn (legacy Lib) i am here, adding custom pieces and prefabs with couple of simple examples and informations/

**Where's the problem?**
Well. For peoples with knowledge in Unity and overall knowledge into C#, the ExampleMod can be pretty useless as they know the existing Unity behavior (no offence to no one). But also for amateurs or peoples who just started an adventure with mods it can be a bit complicated and hard.

**Why?**
Overall lib possibilities are implemented into single file/mod (of course some of them are separated to navigate carefully). I think it can be a bit too much to understand what's going on in this example.

**What to do?**
Keep the main example and copy/refactor it for single elements like "ExampleItem", "ExampleArmor", "ExamplePiece", "ExampleStatus", "ExampleHud". Maybe a lot of work but i think all of that will significantly reduce the questions about that (for better example just put 2 test items inside per one class).

**Cons:**
I can't start the JVL fun today and maybe someone will be mad.

**Pros:**
I think that everyone will be thankfull for that. Especially persons without knowledge about C#, Unity or Valheim modding.

Best regards!
Love for Jotunn.

**Comment by sirskunkalot** [comment]
Hi Raelaziel,

you are talking about TestMod?
https://github.com/Valheim-Modding/Jotunn/blob/dev/TestMod/TestMod.cs

Problem here is that some of the parts interact. For example the EvilSword (introduced in AddClonedItems) also has a custom input (in AddInputs), which is then referenced in Update(). I think that separation would maybe confuse the reader a bit more? But we can try it and look how it turns out. 

Thanks for the suggestion :)

PS: I felt the same way when starting out with Valheim modding (no former C# or Unity knowledge) and saw the examples on ValheimLib and JötunnLib. But when you get accustomed to it all the little parts and bits come together and make very much sense.
