### ISSUE TITLE
MMMHOOK and publicize

### ISSUE THREAD

**Issue by Igmat** [Valheim-Modding/Jotunn#149]
https://github.com/Valheim-Modding/Jotunn/blob/2c062627f76e08186e9bb901c0e7dae324f82d03/JotunnBuildTask/GenerateMMHook.cs#L48

Check here looks only for `MMMHOOK` generated hash - in most cases it's enough.
But if you have generated `MMMHOOK` (using Vortex plugin for example, which is required for ValheimLib) and don't have `publicized` assemblies second one won't be generated by your prebuild task.

**Comment by sirskunkalot** [comment]
Hey Igmat,

I don't get it tbh. What is the problem with Vortex and Jötunn? The .hash files in the MMHOOK folder are generated by the JotunnBuildTask (when enabled). They are the hashes of the vanilla Valheim assembly files, not the MMHOOK ones. One might argue that the MMHOOK folder is not the best place for Jötunn generated hash files. But does Vortex generate own .hash files? Or is the problem that we overwrite the MMHOOK files with Jötunn?

Please elaborate.

**Comment by paddywaan** [comment]
So, VL doesn't require vortex, functions perfectly fine with out it in fact. 

In regards to the generated assemblies, this is aweful. In order to acquire that from the native binary it must have been both publicised and then hooks generated on the now public method sigs. While yes, this should actually work it's definitely not recommended. Honestly if this is something vortex is doing, they should reconsider their approach also.

What exactly do you mean by: 
> But if you have generated MMMHOOK (using Vortex plugin for example, which is required for ValheimLib) and don't have publicized assemblies second one won't be generated by your prebuild task.

? Our build task will fail to generate our needed references if they already exist due to vortex creating the assembly_publiblicised?

**Comment by Algorithman** [comment]
Adressed in #158
