### ISSUE TITLE
[BUG] - Config not actually being imposed upon end user

### ISSUE THREAD

**Issue by sbtoonz** [Valheim-Modding/Jotunn#226]
User Expectation:
When using IsAdminOnly = true  configuration values from server are given to client upon connect 

Reaction:
When Client alters values and connects, the values say they are imposed from server. Client still holds their local version though. 

This use case is probably the culprit if I had to guess. 
It appears that the cfg is not being effected if an end user has altered this config at any point 

Example code:
https://github.com/sbtoonz/RunicSwords/blob/master/JotunnModStub/RuneSwords.cs#L479

**Comment by Algorithman** [comment]
Is it really not synchronized by the server or is it maybe just not written locally?
Another thing is: Examine your config thoroughly. BepInEx keeps orphaned entries. If you changed entries in code, the old ones might still be in the config file (normally at the top, since they're the older ones).

**Comment by sbtoonz** [comment]
steps to reproduce:

1)Install mod on client and server 
2)Admin login to server and make settings changes 
3) User (non server admin) install mod local
4) User logs LOCAL world and makes changes
5) User LOGS off (not quit)
6) User logs REMOTE world 
7) User has settings from step 4 when logging into remote world mentioned in step 1/2

just tried with clean bepinex install and validated logs to ensure jotunn was not considering this person "admin" by some fault

**Comment by Algorithman** [comment]
Just checked it and it worked as intended. 
Configuration is sent to client and values are applied (in my test blast furnace max ore amount) and also shown in the settings tab.

What you experience is something completely different:
You add prefabs and want them to enable/disable (and other stuff) on a configuration change. But you don't have any code for applying the changed values.

First something in general: Config entries should be made as soon as possible (call your ConfigDeploy in Awake instead of LoadgameFabs). If they are created after synchronization, they would not work as intended (not the case here, but for future reference)

As for the bugfix:
Option 1: On your plugin's config, subscribe to the SettingsChanged event and then change the values in your prefabs accordingly (be aware that it will be triggered for each changed value) or make multiple seperate methods and subscribing them to the config entries SettingsChanged events.

Option 2: We also could add an event, triggering right after the server configuration is applied. But this wouldn't trigger on local games. So other troubles would arise from that.

**Comment by sbtoonz** [comment]
Implementation failure on my end will refactor code to adjust - ( this is kind of what I assumed ;) )
