### ISSUE TITLE
[FEATURE] Add mod name to custom items

### ISSUE THREAD

**Issue by MSchmoecker** [Valheim-Modding/Jotunn#286]
**User Story**
As a mod author I want to know the mod name of of a custom Item/Piece/Prefab so that I can display it.

**Envisioned Solution**
When a mod is adding an Item/Piece/Prefab it has always to provide the name of the mod. Additionally there needs to be a way to get all added instances, currently all lists are internal with no access methods. This should be a breaking change so everyone is forced to add the mod name, otherwise it would take way to long before it would be used. With H&H this should be  a good opportunity anyway.

**Additional context**
I am the author of [VNEI](https://github.com/MSchmoecker/VNEI) and would like to display the mod name and more important, make it possible to search with @ for a specific mod. When it is embedded here not everyone has to write individual support for VNEI and I don't have to support a lot of other mods individually.

**Comment by sirskunkalot** [comment]
Hey,

actually I have plans for this already and did some thinking about it. I need to check if there is an automated way to to this. Maybe getting the executing Assembly and query BepInEx' chainloader. I really would like to have this as non-breaking since I still got hope that Jötunn can mitigate at least some H&H changes so that old mods which will not be updated any more can still work in some way.

**Comment by sirskunkalot** [comment]
mostly done
