### ISSUE TITLE
Revise SkillManager

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#307]
cheat raise and reset should be IL
custom skills should be injected into the consolecommand's param list

**Comment by MSchmoecker** [comment]
I think transpilers should only be used when it's really necessary. There is a bit of code duplication but otherwise no need as they are just cheat commands. Most other mods that add skills write prefixes in the same way, too.
Custom skills are now added in the autocomplete with patch 2.10.4.

Closing this for now.
