### ISSUE TITLE
[FEATURE] Allow custom commands to set the isCheat flag

### ISSUE THREAD

**Issue by joeyparrish** [Valheim-Modding/Jotunn#315]
**User Story**
As a mod developer, I want to add a custom command that is hidden behind "devcommands".

**Envisioned Solution**
This should be easily done by adding a field to Jotunn's `ConsoleCommand` that corresponds to the `Terminal.ConsoleCommand.IsCheat` flag.

**Additional context**
None that I can think of.

I will put together a pull request if there are no objections.

**Comment by sirskunkalot** [comment]
Hi,

thanks for your input. That is already planned and will be implemented soon.

**Comment by sirskunkalot** [comment]
see #293

**Comment by sirskunkalot** [comment]
Oh, just saw that: "I will put together a pull request if there are no objections."

Absolutely no objections from my side ;)

**Comment by joeyparrish** [comment]
Great, thanks!  I'll see what I can do.  Though I can build my mod from Linux with Mono, I'm still trying to build Jotunn from source with Mono to test my changes.  Any advice?

It looks like you have GitHub Actions set up and that it produces build artifacts.  Would it be reasonable to send a PR and verify it by downloading the build artifacts from Actions?

**Comment by sirskunkalot** [comment]
I don't have any first hand experience with building Jötunn under Linux unfortunately. But you could take a look at the github action, maybe that helps since that also uses a Linux container to build the artifacts (so I count that as second hand experience then ;)). https://github.com/Valheim-Modding/Jotunn/blob/dev/.github/workflows/tag-release.yml - I guess especially the tool chain might be of interest there?

If you have a hard time setting it up, I can just implement it with the other planned stuff in the referenced issue. It is not a big deal actually, like you said.
