### ISSUE TITLE
Jotunn Banana Texture Error

### ISSUE THREAD

**Issue by mitchelljtroyer** [Valheim-Modding/Jotunn#394]
[Warning:Jotunn.Managers.PrefabManager] Failed to clone prefab, name already exists: Banana
[Error  :   jtv.Jtv] Object reference not set to an instance of an object  at jtv.Jtv.AddItems () [0x00120] in <ae2be70e663543068eaeac2c33eca023>:0

Game works just fine but I receive this error in logs while playing.

**Comment by MSchmoecker** [comment]
This is likely a mod conflict between 'Journey To Valhalla' and another mod. Internal item names must be unique because the game identifies them by their prefab name, thus an error is thrown here.

Please open a new issue at the [Journey To Valhalla](https://github.com/thedefside/journey_to_valhalla) repo.

**Comment by mitchelljtroyer** [comment]
Thanks! I'll look through for the conflict.
