### ISSUE TITLE
[BUG] Jotunn 2.12.1 breaks F5 console on game version 0.217.7 (n-7)

### ISSUE THREAD

**Issue by andrewklamut** [Valheim-Modding/Jotunn#402]
Details:
Jotunn Version: 2.12.1
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): Consistent(100%)

**Problem Description:**
As of this moment, download Valheim [public-test]. Set -console launch parameter in steam. Install Bepinex and Jotunn 2.12.1. Launch Valheim. Press F5 to access console

**Expected Behaviour:**
F5 opens console

**Actual Behaviour:**
Console will not open. Need to remove Jotunn 2.12.1 to access console on Valheim [public-test] 0.217.7 (n-7)

**Link to your server's and client's LogOutput.log**
Upload to https://pastebin.com or simliar service

**Comment by MSchmoecker** [comment]
Thanks for the report.
The bug is known and will be fixed when the PTB is released as stable.

You can try out the Jotunn test release, it's compiled against the PTB: [Jotunn-2.12.2-preview-1.zip](https://github.com/Valheim-Modding/Jotunn/files/11913479/Jotunn-2.12.2-preview-1.zip)
Although note, it's not recommended to play with mods in the PTB as anything may break.

**Comment by MSchmoecker** [comment]
This is now already fixed in Jotunn 2.12.3, where the console commands work for both Valheim 0.216.9 and the PTB release, so there will be a smoother transition when the game updates
