### ISSUE TITLE
[DOC]Project Template features by Ihor Chulinda #6413

### ISSUE THREAD

**Issue by paddywaan** [Valheim-Modding/Jotunn#48]
see: https://github.com/Valheim-Modding/ExampleMod/pull/1

A lot of stuff he we should consider including in a project template.

**Comment by sirskunkalot** [comment]
Beg to differ. All the devops/gh stuff is too much for a truly generic stub. Even push to Nexus? UnityProject is not able to be shared via github. No docs at all.

**Comment by paddywaan** [comment]
Due to the complexity of GH actions, lack of documentation, and a target focus towards a template/boilerplate for users of all levels, those who would benefit from GH actions and automations are capable of writing themselves, however would confuse any new modders. After discussing this with the team we do not feel it would be appropriate to include this inside a boilerplate project.

**Comment by Igmat** [comment]
> No docs at all.

I'm working on them:)

> UnityProject is not able to be shared via github.

Why is that? I have [such project](https://github.com/Igmat/ChestReloadedPlugin). What am I missing?

> All the devops/gh stuff is too much for a truly generic stub.

Just wondering, why? :) What is wrong with automated flow instead of manual compiling and uploading?

**Comment by sirskunkalot** [comment]
Hey Igmat,

> > No docs at all.
> 
> I'm working on them:)

Glad to hear that.

> > UnityProject is not able to be shared via github.
> 
> Why is that? I have [such project](https://github.com/Igmat/ChestReloadedPlugin). What am I missing?

That was actually me being stupid, I apologise.

> > All the devops/gh stuff is too much for a truly generic stub.
> 
> Just wondering, why? :) What is wrong with automated flow instead of manual compiling and uploading?

That is what lead me to that rude statement. It is against my fundamental understanding of an example/stub project which is intended to include the bare basics for someone else to get going with whatever it is an example for. Including these CI/devops things at all and prioritise them instead of making a clear, written documentation and actually help people getting started is, well, not helpful at all IMHO. You might force someone to even deal with more unknown stuff with the "example project" than he wanted to by getting an "example project" in the first place. The original reviewers may have another opinion about it, it got merged to the repo. So yeah, that's just my 2 cents on that matter.

**Comment by Igmat** [comment]
My goal is to make such repo that user's SHOULD NOT think about other technologies, but still get benefits of automation. I agree that missing documentation might be really misleading, so I'm working on docs that show step by step how to work with proposed structure;)
