### ISSUE TITLE
Add transition documents for current JotunnLib/ValheimLib users 

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#57]
We should add a section to the documentation, with code examples, that explains how to transition existing mods from ValheimLib and JotunnLib to the new combined Jotunn lib.

Requirements: 
- [x] Adding JVL to existing project
- [x] Transition guide for JotunnLib
- [x] Transition guide for ValheimLib

**Comment by paddywaan** [comment]
Redundant documentation. Anything that belongs in a "transition" document, also belongs in the tutorials. Just keep the documentation unified in one place instead of designing it around a slightly different approach. The developers already have existing code and the managers for the most part remain in the same style for JL, and entity abstractions are the same for VL. Any confusion for transition can be resolved in the existing documentation.

**Comment by paddywaan** [comment]
Yeah, we miss our core audience if we have no explicit transition document. we may have made "fresh start" easy, but devs wont be excited to make progress unless they can also transition easily.

**Comment by sirskunkalot** [comment]
Also: a quick start. "Create Environment.props, download nuget, ???, profit"

Without Env.props the project does not load anymore. Thats, ummmm, not beneficial?!

**Comment by Algorithman** [comment]
That can be resolved with a conditional import in the csproj
But then we also should print a conditional error message if it could not be imported

**Comment by sirskunkalot** [comment]
base is done in #165 and #166.
