### ISSUE TITLE
chore: Generate MMHOOK DLLs at runtime

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#64]
Look into how we can generate the MMHOOK publicized assemblies at runtime, when Jotunn is loaded. This way, we won't need to ship the DLLs with the library, and they'll always be up-to-date for users. Additionally, it should be less cumbersome for users to deal with installing our library if there's less DLLs for them to fetch,

**Comment by paddywaan** [comment]
Hookgen is exactly the process of generating hooks at runtime. We can not do better than this, nor fody weave it into the plugin as the generated dll's are a dependency of our plugin, and must be run during patcher init rather than plugin init.

However, we can pre-package `MMHOOK` folder alongside our plugin to ensure that at the very least the user has **a** version of mmhook, even if it is not the latest. We would also keep the hookgen dependency and folder structure in this scenario such that hookgen will overwrite any stale dll's during init.

One possible issue I can see with this, is there will exist some users who benefit from this implementation because they were lazy/ignorant of the hookgen dependency, who will continue running using MMHOOK's without a hookgen in place, incorrectly assuming it will work forever. It will not. Eventually method signatures will change, and eventually one which a plugin depends on will change, and then *suddenly* "the update broke the game! Mr. plugin dev please fix your plugin, it doesn't work!".

The end result of this will that plugin dev's will potentially take the brunt of feedback and bug reports instead of either us or mmhook. When these issues arise, they will no longer be our issues to fix.


The other option, is that we just include the hookgen dependency itself, cutting out the "mmhook" middleman. This would resolve the issue with passing the problem down the line, however it does require us packaging hookgen. I'd only be against this idea from the perspective that the dependency already exists and can be maintained through thunderstore/nexus, however I do understand the want of not needing to acquire dependencies separately. This likely raises the least issues and resolves most concerns.

**Comment by paddywaan** [comment]
Resolution is to package HookGen side by side with lib to allow for greater interoperability with few perceived downsides. Issue closed.
